# Generated by Django 3.2.4 on 2021-10-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryoptions',
            name='delivery_window',
            field=models.CharField(help_text='Required', max_length=255, verbose_name='delivery_method'),
        ),
    ]
